<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarageSpace.NotificationService.Repository.Interfaces\GarageSpace.NotificationService.Repository.Interfaces.csproj" />
    <ProjectReference Include="..\GarageSpace.NotificationService.Services.Interfaces\GarageSpace.NotificationService.Services.Interfaces.csproj" />
  </ItemGroup>

</Project>
