<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TaranSoft.MyGarage.NotificationService-6127784e-9540-4a7f-9ba3-d459c66d3df2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GarageSpace.Contracts" Version="0.2.1" />
    <PackageReference Include="MassTransit" Version="8.1.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarageSpace.NotificationService.Repository\GarageSpace.NotificationService.Repository.csproj" />
    <ProjectReference Include="..\GarageSpace.NotificationService.Services.Interfaces\GarageSpace.NotificationService.Services.Interfaces.csproj" />
    <ProjectReference Include="..\GarageSpace.NotificationService.Services\GarageSpace.NotificationService.Services.csproj" />
    <ProjectReference Include="..\GarageSpace.NotificationService.Templates\GarageSpace.NotificationService.Templates.csproj" />
  </ItemGroup>
</Project>
